package com.koval.trainingplannerbackend.training.history;

import com.koval.trainingplannerbackend.auth.UserRepository;
import com.koval.trainingplannerbackend.club.feed.SessionCompletedEvent;
import com.koval.trainingplannerbackend.club.session.ClubTrainingSession;
import com.koval.trainingplannerbackend.club.session.ClubTrainingSessionRepository;
import com.koval.trainingplannerbackend.coach.CoachService;
import com.koval.trainingplannerbackend.coach.ScheduledWorkoutService;
import com.koval.trainingplannerbackend.config.exceptions.ValidationException;
import com.koval.trainingplannerbackend.goal.RaceGoalService;
import com.koval.trainingplannerbackend.race.Race;
import com.koval.trainingplannerbackend.training.metrics.TssCalculator;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Lifecycle for completed workout sessions: save orchestration, linking, patching, and deletion.
 * Read-only window queries live in {@link SessionHistoryQueryService}; FIT file storage lives in
 * {@link SessionFitFileService}.
 */
@Service
public class SessionService {

    private static final Logger log = LoggerFactory.getLogger(SessionService.class);

    private final CompletedSessionRepository repository;
    private final AnalyticsService analyticsService;
    private final UserRepository userRepository;
    private final CoachService coachService;
    private final ScheduledWorkoutService scheduledWorkoutService;
    private final SessionAssociationService associationService;
    private final ClubTrainingSessionRepository clubTrainingSessionRepository;
    private final ApplicationEventPublisher eventPublisher;
    private final SessionFitFileService fitFileService;
    private final RaceGoalService raceGoalService;

    public SessionService(CompletedSessionRepository repository,
                          AnalyticsService analyticsService,
                          UserRepository userRepository,
                          CoachService coachService,
                          ScheduledWorkoutService scheduledWorkoutService,
                          SessionAssociationService associationService,
                          ClubTrainingSessionRepository clubTrainingSessionRepository,
                          ApplicationEventPublisher eventPublisher,
                          SessionFitFileService fitFileService,
                          RaceGoalService raceGoalService) {
        this.repository = repository;
        this.analyticsService = analyticsService;
        this.userRepository = userRepository;
        this.coachService = coachService;
        this.scheduledWorkoutService = scheduledWorkoutService;
        this.associationService = associationService;
        this.clubTrainingSessionRepository = clubTrainingSessionRepository;
        this.eventPublisher = eventPublisher;
        this.fitFileService = fitFileService;
        this.raceGoalService = raceGoalService;
    }

    /** Prefix used to derive a {@code groupId} from a raceId so race-classified sessions auto-bundle. */
    static final String RACE_GROUP_ID_PREFIX = "race-";

    /** True if the given groupId was generated by race classification (vs. user-set brick). */
    static boolean isRaceDerivedGroupId(String groupId) {
        return groupId != null && groupId.startsWith(RACE_GROUP_ID_PREFIX);
    }

    /**
     * Save a completed session: compute metrics, auto-associate, link to schedule, update user load.
     */
    public CompletedSession saveSession(CompletedSession session, String userId) {
        prepareSession(session, userId);
        deleteSyntheticIfLinked(session);

        CompletedSession saved = repository.save(session);

        postSaveSideEffects(saved, userId);
        eventPublisher.publishEvent(new SessionCompletedEvent(saved));
        return saved;
    }

    /**
     * Manually link a session to a scheduled workout. Clears any pending suggestion since
     * the user has now made an explicit choice.
     */
    public CompletedSession linkSessionToSchedule(String sessionId, String scheduledWorkoutId, String userId) {
        CompletedSession session = findOwnedSession(sessionId, userId);
        if (session == null) return null;

        clearPreviousLinkIfDifferent(session, scheduledWorkoutId);

        associationService.deleteSyntheticSessionForSchedule(scheduledWorkoutId);

        session.setScheduledWorkoutId(scheduledWorkoutId);
        session.setSuggestedScheduledWorkoutId(null);
        session.setSuggestionScore(null);
        session.setUnplanned(null);
        CompletedSession saved = repository.save(session);
        tryMarkCompleted(scheduledWorkoutId, saved);
        return saved;
    }

    /** Ranked link candidates for the picker (±3 days, same sport, PENDING, unlinked). */
    public List<SessionAssociationService.LinkCandidate> listLinkCandidates(String sessionId, String userId) {
        CompletedSession session = findOwnedSession(sessionId, userId);
        if (session == null) return List.of();
        return associationService.listCandidates(session);
    }

    /**
     * Clear the pending auto-suggestion without committing to a link.
     * The session remains an orphan but won't re-prompt unless a new suggestion is generated.
     */
    public CompletedSession dismissSuggestion(String sessionId, String userId) {
        CompletedSession session = findOwnedSession(sessionId, userId);
        if (session == null) return null;
        session.setSuggestedScheduledWorkoutId(null);
        session.setSuggestionScore(null);
        return repository.save(session);
    }

    /**
     * Mark the session as not part of any planned workout. Suppresses future suggestion prompts
     * and clears any pending suggestion.
     */
    public CompletedSession markUnplanned(String sessionId, String userId) {
        CompletedSession session = findOwnedSession(sessionId, userId);
        if (session == null) return null;
        session.setUnplanned(true);
        session.setSuggestedScheduledWorkoutId(null);
        session.setSuggestionScore(null);
        return repository.save(session);
    }

    /** Races the athlete has set as goals whose scheduledDate matches the session date. */
    public List<Race> listRaceCandidates(String sessionId, String userId) {
        CompletedSession session = findOwnedSession(sessionId, userId);
        if (session == null || session.getCompletedAt() == null) return List.of();
        return raceGoalService.findRacesForAthleteOnDate(userId, session.getCompletedAt().toLocalDate());
    }

    /**
     * Classify a session against a race day. RACE bundles the session into the race chain via
     * a race-derived groupId; WARMUP marks it race-day but separate; NONE just dismisses the prompt.
     */
    public CompletedSession classifyRace(String sessionId, String raceId, RaceRole role, String userId) {
        if (role == null) {
            throw new ValidationException("raceRole is required");
        }
        CompletedSession session = findOwnedSession(sessionId, userId);
        if (session == null) return null;

        if (role == RaceRole.RACE || role == RaceRole.WARMUP) {
            if (raceId == null || raceId.isBlank()) {
                throw new ValidationException("raceId is required for RACE and WARMUP roles");
            }
            if (!raceGoalService.isRaceInGoals(userId, raceId)) {
                throw new ValidationException("Race is not in the athlete's goals");
            }
            session.setRaceId(raceId);
        } else {
            session.setRaceId(null);
        }

        session.setRaceRole(role);

        if (role == RaceRole.RACE) {
            session.setGroupId(RACE_GROUP_ID_PREFIX + raceId);
        } else if (isRaceDerivedGroupId(session.getGroupId())) {
            // Demoting to WARMUP / NONE — undo any race-derived bundling we previously set.
            session.setGroupId(null);
        }

        return repository.save(session);
    }

    /**
     * Unlink the session from its scheduled workout (undo of auto- or manual-link).
     * Reverts the scheduled workout back to PENDING so it shows up in the picker again.
     */
    public CompletedSession unlinkFromSchedule(String sessionId, String userId) {
        CompletedSession session = findOwnedSession(sessionId, userId);
        if (session == null) return null;
        String swId = session.getScheduledWorkoutId();
        if (swId == null) return session;

        session.setScheduledWorkoutId(null);
        CompletedSession saved = repository.save(session);
        try {
            scheduledWorkoutService.revertToPending(swId);
        } catch (IllegalArgumentException | IllegalStateException e) {
            log.warn("Failed to revert scheduled workout {} to pending: {}", swId, e.getMessage());
        }
        return saved;
    }

    /**
     * Manually link a session to a club training session.
     */
    public CompletedSession linkSessionToClubSession(String sessionId, String clubSessionId, String userId) {
        CompletedSession session = findOwnedSession(sessionId, userId);
        if (session == null) return null;

        ClubTrainingSession clubSession = clubTrainingSessionRepository.findById(clubSessionId).orElse(null);
        if (clubSession == null || !clubSession.getParticipantIds().contains(userId)) return null;

        session.setClubSessionId(clubSessionId);
        CompletedSession saved = repository.save(session);
        eventPublisher.publishEvent(new SessionCompletedEvent(saved));
        return saved;
    }

    /**
     * Patch session fields (currently supports RPE).
     */
    public CompletedSession patchSession(String id, Map<String, Object> body, String userId) {
        CompletedSession session = findOwnedSession(id, userId);
        if (session == null) return null;

        applyRpePatch(session, body);
        applyGroupIdPatch(session, body, userId);

        CompletedSession saved = repository.save(session);
        analyticsService.recomputeAndSaveUserLoad(userId);
        return saved;
    }

    /**
     * Delete a session and its associated FIT file.
     */
    public boolean deleteSession(String id, String userId) {
        return repository.findById(id)
                .filter(s -> userId.equals(s.getUserId()))
                .map(s -> {
                    fitFileService.deleteFitFileQuietly(s.getFitFileId());
                    repository.delete(s);
                    return true;
                })
                .orElse(false);
    }

    public List<CompletedSession> listSessions(String userId) {
        return repository.findByUserIdOrderByCompletedAtDesc(userId);
    }

    public Page<CompletedSession> listSessions(String userId, Pageable pageable) {
        return repository.findByUserIdOrderByCompletedAtDesc(userId, pageable);
    }

    /**
     * Retrieve a single session by ID, visible to the session owner or their coach.
     */
    public Optional<CompletedSession> getSession(String userId, String sessionId) {
        return repository.findById(sessionId)
                .filter(s -> userId.equals(s.getUserId()) || isCoachOfOwner(userId, s.getUserId()));
    }

    /**
     * List completed sessions for a user within a date range, suitable for calendar views.
     */
    public List<CompletedSession> listForCalendar(String userId, LocalDate start, LocalDate end) {
        return repository.findByUserIdAndCompletedAtBetween(
                userId, start.atStartOfDay(), end.atTime(23, 59, 59));
    }

    private void prepareSession(CompletedSession session, String userId) {
        session.setUserId(userId);
        if (session.getCompletedAt() == null) {
            session.setCompletedAt(LocalDateTime.now());
        }

        userRepository.findById(userId).ifPresent(user -> analyticsService.computeAndAttachMetrics(session, user));

        analyticsService.computeBlockDistances(session);

        if (session.getTotalDistance() == null && session.getBlockSummaries() != null) {
            double sum = session.getBlockSummaries().stream()
                    .map(CompletedSession.BlockSummary::distanceMeters)
                    .filter(java.util.Objects::nonNull)
                    .mapToDouble(Double::doubleValue)
                    .sum();
            if (sum > 0) session.setTotalDistance(sum);
        }

        if (session.getScheduledWorkoutId() == null) {
            associationService.tryAutoAssociate(session, userId);
        }
    }

    private void deleteSyntheticIfLinked(CompletedSession session) {
        if (session.getScheduledWorkoutId() != null) {
            associationService.deleteSyntheticSessionForSchedule(session.getScheduledWorkoutId());
        }
    }

    private void postSaveSideEffects(CompletedSession saved, String userId) {
        analyticsService.recomputeAndSaveUserLoad(userId);

        if (saved.getScheduledWorkoutId() != null) {
            tryMarkCompleted(saved.getScheduledWorkoutId(), saved);
        }
    }

    private void clearPreviousLinkIfDifferent(CompletedSession session, String newScheduledWorkoutId) {
        String oldSwId = session.getScheduledWorkoutId();
        if (oldSwId != null && !oldSwId.equals(newScheduledWorkoutId)) {
            associationService.clearScheduledWorkoutLink(oldSwId);
        }
    }

    private void applyRpePatch(CompletedSession session, Map<String, Object> body) {
        if (body.containsKey("rpe")) {
            int rpe = ((Number) body.get("rpe")).intValue();
            session.setRpe(rpe);
            // Recompute TSS only when the existing value is missing or was itself derived from RPE.
            // Power/pace-based TSS is left untouched — RPE just becomes an extra annotation.
            boolean wasRpeBased = Boolean.TRUE.equals(session.getTssFromRpe());
            if (session.getTss() == null || wasRpeBased) {
                double intensityFactor = TssCalculator.intensityFactorFromRpe(rpe);
                double tss = TssCalculator.computeTss(AnalyticsService.loadDurationSeconds(session), intensityFactor);
                session.setTss(Math.round(tss * 10.0) / 10.0);
                session.setIntensityFactor(Math.round(intensityFactor * 1000.0) / 1000.0);
                session.setTssFromRpe(true);
            }
        }
    }

    /**
     * Set or clear the manual {@code groupId}. When setting, the target group must contain only
     * sessions completed on the same calendar day as the patched session — bricks/races are a
     * same-day concept by design.
     */
    private void applyGroupIdPatch(CompletedSession session, Map<String, Object> body, String userId) {
        if (!body.containsKey("groupId")) return;
        Object raw = body.get("groupId");
        if (raw == null || (raw instanceof String s && s.isBlank())) {
            session.setGroupId(null);
            return;
        }
        if (!(raw instanceof String newGroupId)) {
            throw new IllegalArgumentException("groupId must be a string");
        }
        LocalDate day = session.getCompletedAt() != null
                ? session.getCompletedAt().toLocalDate()
                : LocalDate.now();
        List<CompletedSession> existing = repository.findByUserIdAndGroupId(userId, newGroupId);
        for (CompletedSession other : existing) {
            if (other.getId().equals(session.getId())) continue;
            if (other.getCompletedAt() == null || !other.getCompletedAt().toLocalDate().equals(day)) {
                throw new IllegalArgumentException("Cannot group sessions across different days");
            }
        }
        session.setGroupId(newGroupId);
    }

    private CompletedSession findOwnedSession(String sessionId, String userId) {
        return repository.findById(sessionId)
                .filter(s -> userId.equals(s.getUserId()))
                .orElse(null);
    }

    private void tryMarkCompleted(String scheduledWorkoutId, CompletedSession session) {
        try {
            scheduledWorkoutService.markCompleted(scheduledWorkoutId,
                    Optional.ofNullable(session.getTss()).map(Double::intValue).orElse(null),
                    session.getIntensityFactor(),
                    session.getId());
        } catch (IllegalArgumentException | IllegalStateException e) {
            log.warn("Failed to mark scheduled workout {} as completed: {}", scheduledWorkoutId, e.getMessage());
        }
    }

    private boolean isCoachOfOwner(String coachId, String athleteId) {
        try {
            return coachService.isCoachOfAthlete(coachId, athleteId);
        } catch (IllegalArgumentException | IllegalStateException e) {
            return false;
        }
    }
}
